version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./tecnoshop-web-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
